- id: Indoor_Lights_On
  alias: Indoor Lights on at Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: light.turn_on
    entity_id: group.living_room_lights

- id: Indoor_Lights_Off
  alias: Indoor Lights off at Bedtime
  trigger:
    platform: time
    at: "21:00:00"
  action:
    service: light.turn_off
    entity_id: group.living_room_lights
  
- id: Outdoor_Lights_On
  alias: Outdoor Lights on at Night
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: light.turn_on
    entity_id: group.outdoor_lights

- id: Outdoor_Lights_Off
  alias: Outdoor Lights off at Sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:30:00"
  action:
    service: light.turn_off
    entity_id: group.outdoor_lights
    
