- id: letsencrypt_renewal
  alias: Lets Encrypt Renewal
  initial_state: 'on'
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: Indoor_Lights_On
  alias: Indoor Lights on at Sunset
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  action:
  - entity_id: light.lr_dimming_bulb,light.lr_lamp_dimmer,light.lr_lamp_dimmer_2
    service: light.turn_on
  initial_state: 'on'
- id: Indoor_Lights_Off
  alias: Indoor Lights off at Bedtime
  trigger:
  - at: '21:00:00'
    platform: time
  action:
  - entity_id: light.lr_dimming_bulb,light.lr_lamp_dimmer,light.lr_lamp_dimmer_2
    service: light.turn_off
  initial_state: 'on'
- id: Outdoor_Lights_On
  alias: Outdoor Lights on at Night
  trigger:
  - event: sunset
    platform: sun
  action:
  - data: {}
    entity_id: light.garage_doors,light.garage_patio_dimming_bulb,light.front_porch
    service: light.turn_on
  - entity_id: switch.back_porch_lights
    service: switch.turn_on
  - data:
      event: landscapelt_on
    service: ifttt.trigger
  initial_state: 'on'
- id: Outdoor_Lights_Off
  alias: Outdoor Lights off at Sunrise
  trigger:
  - event: sunrise
    offset: +00:30:00
    platform: sun
  action:
  - data: {}
    entity_id: light.garage_doors,light.garage_patio_dimming_bulb,light.front_porch
    service: light.turn_off
  - entity_id: switch.back_porch_lights
    service: switch.turn_off
  - data:
      event: landscapelt_off
    service: ifttt.trigger
  initial_state: 'on'
- id: lock_door
  alias: Lock Garage Door
  trigger:
  - at: '21:00:00'
    platform: time
  action:
  - entity_id: lock.e_garage_entry_door
    service: lock.lock
  initial_state: 'on'
- id: unlock_door
  alias: Unlock Garage Door
  trigger:
  - at: 06:45:00
    platform: time
  action:
  - entity_id: lock.e_garage_entry_door
    service: lock.unlock
  initial_state: 'on'
- id: 8241993d082e478eb2e1b38f2add9213
  alias: Notify if garage left open
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.vision_zg8101_garage_door_detector_sensor
    - binary_sensor.vision_zg8101_garage_door_detector_sensor_2
    to: 'on'
    for:
      minutes: 3
  action:
  - service: ifttt.trigger
    data:
      event: garage_open
  - service: notify.beau_pushbullet
    data:
      message: Garage door was left open
      title: ''
  - service: notify.erin_pushbullet
    data:
      message: Garage door was left open
      title: ''
  - service: notify.alexa_media
    data:
      target:
      - media_player.everywhere
      data:
        type: announce
      message: A garage door was left open.
- id: '1563552008255'
  alias: Garage Door - Single Opening
  trigger:
  - entity_id: binary_sensor.vision_zg8101_garage_door_detector_sensor_2
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      target:
      - media_player.everywhere
      data:
        type: announce
      message: The double garage door is opening.
- id: '1563552930551'
  alias: Garage Door - Double Opening
  trigger:
  - entity_id: binary_sensor.vision_zg8101_garage_door_detector_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      target:
      - media_player.everywhere
      data:
        type: announce
      message: The single garage door is opening
- id: '1572470799220'
  alias: Coop
  description: ''
  trigger:
  - below: '28'
    entity_id: sensor.dark_sky_apparent_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      event: coop_on
    service: ifttt.trigger
- id: '1590163494482'
  alias: Restore Climate
  description: Due to windows and doors closed
  trigger:
  - entity_id: binary_sensor.e_bedroom_window_alarm
    for: 00:02:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.w_bedroom_window_alarm
    for: 00:02:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.n_dining_window_alarm
    for: 00:02:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.s_kitchen_window_alarm
    for: 00:02:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.back_porch_door
    for: 00:02:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.s_kitchen_window_2
    for: 00:02:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.n_dining_window_2
    for: 00:02:00
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.e_bedroom_window_alarm
    state: 'off'
  - condition: state
    entity_id: binary_sensor.w_bedroom_window_alarm
    state: 'off'
  - condition: state
    entity_id: binary_sensor.n_dining_window_alarm
    state: 'off'
  - condition: state
    entity_id: binary_sensor.s_kitchen_window_alarm
    state: 'off'
  - condition: state
    entity_id: binary_sensor.back_porch_door
    state: 'off'
  - condition: state
    entity_id: input_boolean.climate_state
    state: 'on'
  action:
  - data:
      preset_mode: none
    entity_id: climate.main
    service: climate.set_preset_mode
  - data:
      message: Thermostat has been restored
    service: notify.beau_pushbullet
  - data:
      data:
        type: announce
      message: Thermostat has been restored
      target:
      - media_player.everywhere
    service: notify.alexa_media
  - data: {}
    entity_id: input_boolean.climate_state
    service: input_boolean.turn_off
- id: '1590164413627'
  alias: Turn off Climate
  description: Due to open door or window
  trigger:
  - entity_id: binary_sensor.e_bedroom_window_alarm
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.w_bedroom_window_alarm
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.n_dining_window_alarm
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.s_kitchen_window_alarm
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.back_porch_door
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.s_kitchen_window_2
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.n_dining_window_2
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.climate_state
    state: 'off'
  action:
  - data:
      preset_mode: away
    entity_id: climate.main
    service: climate.set_preset_mode
  - data:
      data:
        type: announce
      message: Thermostat has been turned off due to an open door or window
      target:
      - media_player.everywhere
    service: notify.alexa_media
  - data:
      message: Thermostat has been turned off due to an open door or window
    service: notify.beau_pushbullet
  - data: {}
    entity_id: input_boolean.climate_state
    service: input_boolean.turn_on
- id: '1590506306244'
  alias: Lock Back Door at Night
  description: ''
  trigger:
  - at: '21:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: lock.back_porch_deadbolt
    state: unlocked
  action:
  - data: {}
    entity_id: lock.back_porch_deadbolt
    service: lock.lock
- id: '1603471969440'
  alias: Notify of Low Garage Temperature
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: de15b8f8ec56452da36723c5a9d641c9
    entity_id: sensor.garage_therm_temp1
    domain: sensor
    below: 38
    above: -100
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - type: is_value
    condition: device
    device_id: de15b8f8ec56452da36723c5a9d641c9
    entity_id: sensor.garage_therm_temp1
    domain: sensor
    below: 38
  action:
  - service: notify.beau_pushbullet
    data:
      message: The garage temperature is low!
  - service: notify.erin_pushbullet
    data:
      message: The garage temperature is low!
  - service: notify.alexa_media
    data:
      data:
        type: announce
      message: The garage temperature is low, check the heater or thermostat
      target:
      - media_player.everywhere
  mode: single
- id: '1608329261918'
  alias: Turn on XMas Lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.xmas
  mode: single
- id: '1608329309993'
  alias: Turn off XMas Lights
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.xmas
  mode: single
- id: '1608336829577'
  alias: Turn on Ext Cord
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.ext_cord
  mode: single
- id: '1608336920574'
  alias: Turn off Ext Cord
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.ext_cord
  mode: single