- id: Set Theme at Startup
  alias: Set theme at startup
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: frontend.set_theme
    data:
      name: NightOwl
- id: letsencrypt_renewal
  alias: Lets Encrypt Renewal
  initial_state: 'on'
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: Indoor_Lights_On
  alias: Indoor Lights on at Sunset
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: -00:45:00
  action:
  - service: light.turn_on
    data:
      entity_id: group.living_room_lights
  - service: light.turn_on
    data:
      entity_id: light.level_6
      brightness: 200
- id: Indoor_Lights_Off
  alias: Indoor Lights off at Bedtime
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:00:00'
  action:
  - service: light.turn_off
    data:
      entity_id: group.living_room_lights
  - service: light.turn_off
    data:
      entity_id: light.level_6
- id: Outdoor_Lights_On
  alias: Outdoor Lights on at Night
  trigger:
  - event: sunset
    platform: sun
  action:
  - data:
      brightness: 255
      entity_id: group.outdoor_lights
    service: light.turn_on
  - data:
      entity_id: switch.inovelli_nzw30s_on_off_switch_scene_switch
    entity_id: switch.inovelli_nzw30s_on_off_switch_scene_switch
    service: switch.turn_on
  - data:
      event: landscapelt_on
    service: ifttt.trigger
  initial_state: 'on'
- id: Outdoor_Lights_Off
  alias: Outdoor Lights off at Sunrise
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunrise
    offset: +00:30:00
  action:
  - service: light.turn_off
    data:
      entity_id:
      - group.outdoor_lights
      - group.landscape_lights
  - service: switch.turn_off
    data:
      entity_id: switch.inovelli_nzw30s_on_off_switch_scene_switch
  - service: ifttt.trigger
    data:
      event: landscapelt_off
- id: lock_door
  alias: Lock Garage Door
  initial_state: 'on'
  trigger:
    platform: time
    at: '20:00:00'
  action:
    service: lock.lock
    entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
- id: unlock_door
  alias: Unlock Garage Door
  initial_state: 'on'
  trigger:
    platform: time
    at: 06:45:00
  action:
    service: lock.unlock
    entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
- alias: Notify if garage left open
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.vision_zg8101_garage_door_detector_sensor
    - binary_sensor.vision_zg8101_garage_door_detector_sensor_2
    to: 'on'
    for:
      minutes: 3
  action:
  - service: ifttt.trigger
    data:
      event: garage_open
  - service: notify.beau_pushbullet
    data:
      message: Garage door was left open
      title: ''
  - service: notify.erin_pushbullet
    data:
      message: Garage door was left open
      title: ''
  - service: notify.alexa_media
    data:
      target:
      - media_player.beau_s_echo
      - media_player.beau_s_2nd_echo_dot
      - media_player.beau_s_echo_dot
      message: Garage Door was Left Open
      data:
        type: tts
        method: speak
  id: 8241993d082e478eb2e1b38f2add9213
- id: '1563552008255'
  alias: Garage Door - Single Opening
  trigger:
  - entity_id: binary_sensor.vision_zg8101_garage_door_detector_sensor_2
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      target:
      - media_player.beau_s_echo
      - media_player.beau_s_2nd_echo_dot
      - media_player.beau_s_echo_dot
      message: Single Garage Door is Opening
      data:
        type: tts
        method: speak
- id: '1563552930551'
  alias: Garage Door - Double Opening
  trigger:
  - entity_id: binary_sensor.vision_zg8101_garage_door_detector_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      target:
      - media_player.beau_s_echo
      - media_player.beau_s_2nd_echo_dot
      - media_player.beau_s_echo_dot
      message: Double Garage Door is Opening
      data:
        type: tts
        method: speak
- id: '1572470799220'
  alias: Coop
  description: ''
  trigger:
  - below: '28'
    entity_id: sensor.dark_sky_apparent_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      event: coop_on
    service: ifttt.trigger
    
- id: '1589818236256'
  alias: Turn off Climate Due to Open Door/Window
  description: ''
  trigger:
   - platform: state
     entity_id:
      - binary_sensor.back_porch_door
      - binary_sensor.front_door
     from: 'closed'
     to: 'open'
     for: 
      minutes: 2
   - platform: state
     entity_id:
      - binary_sensor.e_bedroom_window
      - binary_sensor.n_dining_window
      - binary_sensor.s_kitchen_window
      - binary_sensor.w_bedroom_window
     from: 'off'
     to: 'on'
     for: 
      minutes: 2
  condition: []
  action:
  - data: {}
    entity_id: climate.main
    service: climate.turn_off
  - data:
      message: "Climate has been turned off because a window or door has been open for 2 minutes"
      target:
      - media_player.beau_s_echo
      - media_player.beau_s_2nd_echo_dot
      - media_player.beau_s_echo_dot
    service: notify.alexa_media

- id: 'restoreClimate'
  alias: Restore Climate after Closing Door/Window
  description: ''
  trigger:
   - platform: state
     entity_id:
      - binary_sensor.back_porch_door
      - binary_sensor.front_door
     from: 'open'
     to: 'closed'
     for: 
      minutes: 2
   - platform: state
     entity_id:
      - binary_sensor.e_bedroom_window
      - binary_sensor.n_dining_window
      - binary_sensor.s_kitchen_window
      - binary_sensor.w_bedroom_window
     from: 'on'
     to: 'off'
     for: 
      minutes: 2
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
     entity_id: climate.main
     hvac_mode: auto
  - data:
      message: "Climate has been restored to schedule"
      target:
      - media_player.beau_s_echo
      - media_player.beau_s_2nd_echo_dot
      - media_player.beau_s_echo_dot
    service: notify.alexa_media