homeassistant:
  name: Crimson
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 4554
  unit_system: imperial
  time_zone: America/Denver
  customize: !include customize.yaml
  packages: !include_dir_named packages
  
python_script:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://192.168.0.131:3218

  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: https://beauhill.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  cors_allowed_origins:
    - http://192.168.0.131:7080
    - http://192.168.0.145
    - https://reformedreality.com
  trusted_networks:
    - 192.168.0.0/24



ifttt:
  key: !secret ifttt_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
mqtt:
  broker: core-mosquitto
  username: !secret mos_username
  password: !secret mos_password
  
sun:

# Weather prediction

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

zwave:
    usb_path: /dev/ttyACM0

#appdaemon:

#hadashboard:
  #dash_url: http://192.168.1.131:5050
  #dash_password: !secret dash_password
  
group: !include groups.yaml
automation: !include automations.yaml


