homeassistant:
  name: Crimson
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1388
  unit_system: imperial
  time_zone: America/Denver
  customize: !include customize.yaml
  packages: !include_dir_named packages
#  auth_providers:
#   - type: trusted_networks
#     trusted_networks:
#       - 192.168.0.0/24
  
group: !include groups.yaml
automation: !include automations.yaml
  
panel_iframe:
#  configurator:
#    title: 'Configurator'
#    icon: 'mdi:wrench'
#    url: https://192.168.0.137:8123/hassio/ingress/core_configurator
    
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
    
# Enables configuration UI
config:

# Enables the frontend
frontend:
  themes: !include themes.yaml

http:
  base_url: https://beauhill.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # Secrets are defined in the file secrets.yaml
#  api_password: !secret http_password
  cors_allowed_origins:
    - http://192.168.0.131:7080
    - http://192.168.0.14
    - htyp://192.168.0.135
    - https://reformedreality.com
    - https://192.168.0.0/24

lovelace:
  mode: yaml

updater:

###############################################################################################
#####END OF MAIN#### 
##############################################################################################

#alexa_media:
#  accounts:
#  - email: !secret amazon_email
#    password: !secret amazon_password
#    url: amazon.com

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#camera:
#  - platform: usps
#    scan_interval: 5
#  - platform: yi
#    name: 'Garage Camera'
#    host: '192.168.1.190'
#    password: 
    
climate:
  - platform: zwave
  - platform: venstar
    host: 192.168.0.43
    
# Discover some devices automatically
discovery:

#device_tracker:
#  platform: owntracks
#  mqtt_topic: "owntracks/#"

ffmpeg:

hacs:
  token: 65f128b934e795e5a76ee9454aba9d030b33961f
  
# Enables support for tracking state changes over time
history:

ifttt:
  key: !secret ifttt_key
  
# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

media_player:
  - platform: spotify
    client_id: !secret spotify_client
    client_secret: !secret spotify_secret
    aliases:
        abc123def456: 'Hassio'
#  - platform: denonavr
#    host: 192.168.0.145
#    name: Man Cave Audio
#    show_all_sources: True
#  - platform: alexa
#    email: !secret amazon_email
#    password: !secret amazon_password
#    url: amazon.com
  - platform: roku
  - platform: yamaha

mqtt:
  broker: m15.cloudmqtt.com
  port: 17884
  username: !secret mqtt_username
  password: !secret mqtt_password

notify:
  - platform: pushbullet
    name: beau_pushbullet
    api_key: !secret BH_Pushbullet_Key
  - platform: pushbullet
    name: erin_pushbullet
    api_key: !secret EH_Pushbullet_Key
  - platform: alexa_media
    name: alexa_media
  
#owntracks:

recorder:
#  db_url: mysql://hassio:CebhWYO81!@core-mariadb/homeassistant?charset=utf8

ring:
  username: !secret ring_username
  password: !secret ring_password


sensor:
  - platform: airthings_wave
    mac: "98:07:2D:43:4C:89"
    name: 'Basement Airthings Wave'
    scan_interval: 120
    
#sensor:
#  - platform: ups
#    username: !secret UPS_Username
#    password: !secret UPS_Password
#    
#  - platform: time_date
#    display_options:
#      - 'time'
#      - 'date'
#      - 'date_time'
#      - 'date_time_iso'
#      - 'time_date'
#      - 'time_utc'
#      - 'beat'

#shell_command:
#  disco_off: echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/ttyACM0
#  disco_on: echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/ttyACM0

stream:

sun:

system_health:

tts:
  - platform: google_translate
    service_name: google_say

#usps:
#    username: !secret USPS_Username
#    password: !secret USPS_Password
  
weather:
  - platform: darksky
    api_key: !secret darksky_key
    
zwave:
    usb_path: /dev/ttyACM0
    network_key: "0x2e, 0xcc, 0xab, 0x1c, 0xa3, 0x7f, 0x0e, 0xb5, 0x70, 0x71, 0x2d, 0x98, 0x25, 0x43, 0xee, 0x0c"
