title: HILL HOME AUTOMATION
background: !include views/background.yaml

#############PAGE 1 - HOME CONTROL#############################################################
views:
  - name: Home
    theme: NightOwlTransparent
    cards:
    - type: horizontal-stack
      cards:
      - type: vertical-stack
        cards:
          - entity: light.linear_wd500z_1_wall_dimmer_switch_level
            name: Garage Doors
            type: light
          - entity: light.linear_lb60z_1_dimmable_led_light_bulb_level
            name: Garage Patio
            type: light
          - entity: light.linear_wd500z_1_wall_dimmer_switch_level_2
            name: Front Porch
            type: light
          - entity: switch.inovelli_nzw30s_on_off_switch_scene_switch
            icon: 'mdi:lightbulb'
            name: Back Porch Lights
            tap_action:
              action: call-service
              service: switch.toggle
            type: entity-button
      - type: vertical-stack
        cards:
          - entity: light.airline_mechanical_zds_100_level
            name: Lamp Dimmer
            type: light
          - entity: light.airline_mechanical_zds_100_level_2
            name: Lamp Dimmer
            type: light
          - entity: light.linear_lb60z_1_dimmable_led_light_bulb_level_2
            name: Lamp Bulb
            type: light
          - type: horizontal-stack
            cards:
             - entity: automation.fence_lights_on
               icon: 'mdi:lightbulb-on'
               tap_action:
                action: call-service
                service: automation.trigger
                service_data:
                  entity_id: automation.fence_lights_on
               type: entity-button
               
             - entity: automation.fence_lights_off
               icon: 'mdi:lightbulb'
               tap_action:
                action: call-service
                service: automation.trigger
                service_data:
                  entity_id: automation.fence_lights_off
               type: entity-button
               
          #- entity: automation.fence_lights_on
          #  icon: 'mdi:lightbulb'
          #  tap_action:
          #   action: call-service
          #   service: automation.trigger
          #   service_data:
          #     entity_id: automation.fence_lights_on
          #  type: entity-button
            
#    - entity: cover.gate_control
#      icon: 'mdi:gate'
#      name: 'Gate'
#      tap_action:
#        action:
#         - service: cover.close_cover
#           data:
#            entity-id: cover.gate_control
#      type: entity-button
      
    - type: entity-button
      icon: 'mdi:gate'
      name: 'Gate'
      tap_action:
        action: call-service
        service: input_boolean.toggle
        service_data:
          entity_id: input_boolean.gate_control
      entity: binary_sensor.neo_coolcam_door_window_detector_sensor
      
    - type: horizontal-stack
      cards: 
        - type: entity-button
          icon: 'mdi:garage'
          name: 'Single Garage Door'
          tap_action:
            action: call-service
            service: input_boolean.toggle
            service_data:
              entity_id: input_boolean.single_garage_door
          entity: binary_sensor.vision_zg8101_garage_door_detector_sensor
          
        - type: entity-button
          icon: 'mdi:garage'
          name: 'Double Garage Door'
          tap_action:
            action: call-service
            service: input_boolean.toggle
            service_data:
              entity_id: input_boolean.double_garage_door
          entity: binary_sensor.vision_zg8101_garage_door_detector_sensor_2
          
          
    - type: horizontal-stack
      cards:
        - entity: lock.kwikset_touchpad_electronic_deadbolt_locked
          icon: 'mdi:lock'
          name: Lock Garage Entry Door
          tap_action:
            action: call-service
            service: lock.lock
          type: entity-button
        - entity: lock.kwikset_touchpad_electronic_deadbolt_locked
          icon: 'mdi:lock-open'
          name: Unlock Garage Entry Door
          tap_action:
            action: call-service
            service: lock.unlock
          type: entity-button
    - type: vertical-stack
      cards:
        - entities:
          - group.all_automations
          show_header_toggle: false
          type: entities
          name: 'Automations'
    icon: 'mdi:home'
    path: default_view
    title: default_view
################################################################################################################################    

##########PAGE 2 - ALARM PANEL#################################################################################################
  - name: Alarm
    theme: NightOwlTransparent
    cards:
      - entity: alarm_control_panel.home_alarm
        name: House Alarm
        states:
          - arm_home
          - arm_away
#          - arm_night
        type: alarm-panel
    icon: 'mdi:blur-radial'
################################################################################################################################

########PAGE 3 - SURVIELLANCE###################################################################################################
  - name: Surveillance
    theme: NightOwlTransparent
    cards:
      - type: vertical-stack
        cards:
        - type: picture-glance
          title: Gate Keypad
          entities:
            - binary_sensor.ring_gate_keypad_ding
            - binary_sensor.ring_gate_keypad_motion
          camera_image: camera.gate_keypad
          camera_view: live
        - camera_image: camera.ptz_camera
          camera_view: live
          entity: camera.ptz_camera
          show_info: false
          title: Driveway Camera
          type: picture-entity
        - camera_image: camera.garage_dogs
          camera_view: live
          entity: camera.garage_dogs
          show_info: false
          title: Garage Dog Kennel
          type: picture-entity
        
        
      - type: vertical-stack
        cards:
        - entity: binary_sensor.back_porch_door
          icon: 'mdi:door'
          name: Back Porch Door
          type: entity-button
        - type: horizontal-stack
          cards:
            - entity: binary_sensor.vision_zg8101_garage_door_detector_sensor
              icon: 'mdi:garage'
              name: Single Garage Door
              type: entity-button
            - entity: binary_sensor.vision_zg8101_garage_door_detector_sensor_2
              icon: 'mdi:garage'
              name: Double Garage Door
              type: entity-button
        - entity: binary_sensor.neo_coolcam_door_window_detector_sensor
          icon: 'mdi:gate'
          name: Gate
          type: entity-button
      - type: map    
        aspect_ratio: 969
        default_zoom: 11
        entities:
          - device_tracker.beauhill_beausphone
          - device_tracker.evaughnhill_erinphone
          - zone.home
      
          
    icon: 'mdi:eye'
    title: Surviellance
###############################################################################################################################
  - name: Climate
    theme: NightOwlTransparent
    cards:
      - type: vertical-stack
        cards: 
        - type: thermostat
          entity: climate.2gig_technologies_ct101_thermostat_iris_heating_1
          name: 'Garage'
        - type: horizontal-stack
          cards:
          - entity: climate.2gig_technologies_ct101_thermostat_iris_heating_1
            name: 'Set Temp to 38'
            tap_action:
              action: call-service
              service: climate.set_temperature
              service_data:
                entity_id: climate.2gig_technologies_ct101_thermostat_iris_heating_1
                temperature: 38
            type: entity-button
            icon: 'mdi:temperature-fahrenheit'
      
          - type: sensor
            entity: sensor.garage_thermostat_battery
            name: ' ' 

    icon: 'mdi:fan'
    path: climate
    title: Climate
##########PAGE 5 - WEATHER######################################################################################################    
  - name: Weather
    theme: NightOwlTransparent
    cards:
      - aspect_ratio: 969
        image: >-
          https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=UDX&brand=wui&num=10&delay=25&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=0&rand=25769976&lat=0&lon=0&label=you       
        type: picture
      - type: iframe
        url: https://embed.windy.com/?44.229,-105.573,6
        aspect_ratio: 80%
      - entities:
          - sensor.dark_sky_apparent_temperature
          - sensor.vision_zp3111_multisensor_4in1_temperature
        hours_to_show: 48
        type: history-graph
      - type: vertical-stack
        cards: 
         - type: sensor
           entity: sensor.dark_sky_temperature
           name: Temperature
           icon: 'mdi:thermometer'
           graph: line
           detail: 2
           hours_to_show: 72
         - type: sensor
           entity: sensor.dark_sky_wind_speed
           graph: line
           detail: 2
           hours_to_show: 72
           name: Wind Speed
           icon: 'mdi:weather-windy'
         - type: sensor
           entity: sensor.dark_sky_wind_gust
           graph: line
           detail: 2
           hours_to_show: 72
           name: Wind Gusts 
           icon: 'mdi:weather-windy'
      - entity: weather.dark_sky
        type: weather-forecast
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.dark_sky_summary_1d
            name: "24 Hour Forecast"
          - type: glance
            title: " "
            entities:
             - entity: sensor.dark_sky_daytime_high_temperature_1d
               name: "High"
             - entity: sensor.dark_sky_overnight_low_temperature_1d
               name: "Low"
             - entity: sensor.dark_sky_wind_speed_1d
               name: "Wind Speed"
             - entity: sensor.dark_sky_precip_probability_1d
               name: "Precip %"

          - type: sensor
            entity: sensor.dark_sky_summary_2d
            name: "48 Hour Forecast"
          - type: glance
            title: " "
            entities:
             - entity: sensor.dark_sky_daytime_high_temperature_2d
               name: "High"
             - entity: sensor.dark_sky_overnight_low_temperature_2d
               name: "Low"
             - entity: sensor.dark_sky_wind_speed_2d
               name: "Wind Speed"
             - entity: sensor.dark_sky_precip_probability_2d
               name: "Precip %"

          - type: sensor
            entity: sensor.dark_sky_summary_3d
            name: "Day 3 Forecast"
          - type: glance
            title: " "
            entities:
             - entity: sensor.dark_sky_daytime_high_temperature_3d
               name: "High"
             - entity: sensor.dark_sky_overnight_low_temperature_3d
               name: "Low"
             - entity: sensor.dark_sky_wind_speed_3d
               name: "Wind Speed"
             - entity: sensor.dark_sky_precip_probability_3d
               name: "Precip %"

          - type: sensor
            entity: sensor.dark_sky_summary_4d
            name: "Day 4 Forecast"
          - type: glance
            title: " "
            entities:
             - entity: sensor.dark_sky_daytime_high_temperature_4d
               name: "High"
             - entity: sensor.dark_sky_overnight_low_temperature_4d
               name: "Low"
             - entity: sensor.dark_sky_wind_speed_4d
               name: "Wind Speed"
             - entity: sensor.dark_sky_precip_probability_4d
               name: "Precip %"
    icon: 'mdi:theme-light-dark'
    path: weather
    title: Weather

################################################################################################################################

#######PAGE 6 - MEDIA CONTROLS#################################################################################################
  - name: Media
    theme: NightOwlTransparent
    cards:
      - type: vertical-stack
        cards:
          - entity: media_player.beau_s_echo
            type: media-control
          - entity: media_player.beau_s_2nd_echo_dot
            type: media-control
          - entity: media_player.beau_s_echo_dot
            type: media-control
          - entity: media_player.everywhere
            type: media-control
      - type: vertical-stack
        cards:
         - entity: media_player.roku_tv
           type: media-control
         - entity: media_player.roku_player
           type: media-control
         - entity: media_player.man_cave_roku
           type: media-control
      - entity: media_player.spotify
        type: media-control
    icon: 'mdi:cast'
    title: Media
    
    
    

