sensor:
  - platform: template
    sensors:
      garage_thermostat_battery:
        friendly_name: "Garage Thermostat Battery"
        value_template: >-
          {%- if states('zwave.garage_thermostat') -%}
            {{ state_attr('zwave.garage_thermostat','battery_level') }}
          {%- else -%}
            'uknown'
          {%- endif -%} 

        icon_template: >-
          {%- if states('zwave.garage_thermostat') -%}
            {% set battery_level = state_attr('zwave.garage_thermostat','battery_level')|int('unknown') %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_level == 'uknown' %}
              mdi:battery
            {% else %}
              {% if battery_round >= 100 %}
                 mdi:battery
               {% elif battery_round > 0 %}
                 mdi:battery-{{ battery_round }}
               {% else %}
                 mdi:battery-alert
               {% endif %}
            {% endif %}
          {%- else -%}
            'unknown'
            mdi:battery-uknown
          {% endif %}
          
        unit_of_measurement: '%'
#        entity_id: zwave.garage_thermostat

automation:
- alias: Battery Low Alert
  trigger:
  - platform: numeric_state
    entity_id: sensor.garage_therm_battery
    below: 20
  action:
  - service: notify.mobile_app_iphone
    data: 
      message: "Garage Thermostat Battery Low!"
      title: ""
      
      
