input_boolean:
  gate_actuate:
    name: Open or Close Gate
    initial: off

automation:
  - alias: Open or Close Gate
    trigger: 
      - platform: state
        entity_id: input_boolean.gate_actuate
        to: 'on'
    action:
      - service: ifttt.trigger
        data: {"event":"gate_opener"}
  - alias: Send Off to Switch
    trigger: 
      - platform: state
        entity_id: input_boolean.gate_actuate
        to: 'off'
    action:
      - service: ifttt.trigger
        data: {"event":"gate_close"}
