input_boolean:
  gate_control:
    name: Gate Control
    initial: off
    icon: mdi:garage
#    icon_template:  >-
#     {% if states.binary_sensor.neo_coolcam_door_window_detector_sensor.state == 'on' %}
#      mdi:gate-open
#     {% else %}
#      mdi:gate
#     {% endif %}


cover:
  - platform: template
    covers: 
      gate_control:
        friendly_name: 'Gate Control'
        open_cover:
          service: ifttt.trigger
          data: {"event":"gate_control"}
        close_cover:
          service: ifttt.trigger
          data: {"event":"gate_control"}
        #stop_cover:
        #  service: ifttt.trigger
        #  data: {"event":"gate_control"}
        icon_template: 
#         {%- if states.binary_sensor.garagedoor.state == 'on' -%}
          mdi:gate
#         {%- else -%}
#         mdi:garage
#         {%- endif -%}

automation:
- alias: Toggle Gate
  trigger: 
  - platform: state
    entity_id: input_boolean.gate_control
    to: 'on'
  action:
   - service: ifttt.trigger
     data: {"event":"gate_control"}
- alias: Toggle Gate Off
  trigger: 
  - platform: state
    entity_id: input_boolean.gate_control
    to: 'off'
  action:
   - service: ifttt.trigger
     data: {"event":"gate_control"}



- alias: Alexa notify if motion at gate
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.ring_gate_keypad_motion
    to: 'on'
  action:
    - service: notify.alexa_media
      data: 
        target: 
          - media_player.beau_s_echo
          - media_player.beau_s_2nd_echo_dot
          - media_player.beau_s_echo_dot
        message: "Motion has been detected at the gate"
        data:
          type: tts
          method: speak


- alias: Alexa notify if ring is pressed
  trigger:
  - platform: state
    entity_id: binary_sensor.ring_gate_keypad_ding
    to: 'on'
  action:
    - service: notify.alexa_media
      data: 
        target:
          - media_player.beau_s_2nd_echo_dot
          - media_player.beau_s_echo
          - media_player.beau_s_echo_dot
        message: "There is someone at the gate"
        data:
          type: tts
          method: speak