automation:
- alias: Office Heat Pump Cool
  description: ''
  trigger:
  - platform: time
    at: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: 'sensor.dark_sky_apparent_temperature'
        above: 78
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
  action:
  - service: remote.send_command
    data:
      device: Heat Pump
      command:
       #Power On
       - b64:JgAGAWw1Dg0PDQ4oDg4OKA4NDg4ODQ0pDygODQ4ODg0OKA8nDw0ODg4NDg4ODQ4ODg0ODg4NDg4ODQ4ODg0OKA8NDg0PDQ4NDw0ODQ8NDigODg4NDg4ODQ4oDygOKA4oDigOKA4oDygODQ4ODigODQ8NDg0PDQ4NDw0ODQ8NDigOKA4ODg0OKA8NDg0PDQ4NDw0OKA4ODg0ODg4oDg0PDQ4NDw0ODQ8NDg0PDQ4ODigODQ4ODg0ODg4NDg4ODQ4ODg0PDQ4NDw0ODQ8NDg0ODg4NDw0ODQ8NDg0PDQ4NDw0ODg4NDg4MDw4ODg0ODg4NDigPDQ4NDigPKA4NDigPJw8NDigODg4ADQU=
       #Set Mode to Cool
       - b64:JgAGAWs2DQ8MDw0pDg4MKg0PDA8MEA0pDSkNDg4ODQ4NKg0pDQ4NDw0ODQ8MDw0PDA8NDw0ODQ8MDw4ODQ4OKQ0ODQ8NDg0PDQ4NDwwPDSkODgwPDQ8MDw0qDSkNKQ0pDSkNKQ4pDSkNDg4ODCoNDg0PDA8ODgwPDQ8NDwwPDSkNKQ4ODA8NDw0ODQ8MDw4pDQ4NKQ0PDSkNDg4ODBAMDwwQDQ4NDw0ODQ8NDg0PDCoNDg4ODQ4ODgwPDQ8NDg0PDA8ODg0ODQ8NDg0PDQ8MDwwQDA8NDwwPDQ8MDw0PDA8NDw0ODQ8MDw0PDA8NDw0ODigODg0ODikNKQ0pDSkNDw0ODSkODg0ADQU=
       #Set Temp to 68
       - b64:JgAGAWo2Dg4MDw0pDg4MKg0PDA8NDw0pDSkMEAwPDQ8MKgwqDQ4NDwwQDA8MDw0PDBANDg0PDQ4NDwwPDQ8MKgwPDQ8NDg0PDQ4NDw0ODSoMDw0PDA8NDwwqDCoMKg0pDSkOKQ0pDSkNDg4ODCoNDwwPDQ8MDw0PDQ4NDwwPDSkOKQ0ODQ8MDw0PDA8NDwwPDQ8NKQwPDg4NDg0PDQ4NDw0ODQ8MEA0ODBAMDw0PDSkNDg0PDA8NDw0ODQ8NDg0PDA8ODg0ODQ8MDw4ODBANDgwPDg4MEAwPDBAMDwwQDA8NDw0ODQ8MDw0PDA8NDwwPDSkNDwwPDQ8NDg4ODQ4NDwwqDSkNDwwADQU=
       #Swing
       - b64:JgAGAWo3DA8NDwwqDQ8NKQwPDQ8MDw0pDSoNDg0PDQ4NKQ4oDg4MEA0ODBAMDwwQDA8NDwwPDQ8NDg0PDA8NKQ4ODA8ODgwPDg4MDw0PDCoNDwwPDQ8MDw0pDSkNKgwqDSkNKQ0pDigNDwwQDCoNDg0PDA8NDwwPDQ8NDg0PDCoNKQ0PDQ4NDwwPDQ8MDw0pDQ8NKQwQDA8MEAwqDA8NDwwPDg4MDw0PDA8NDwwPDSoNDg0PDA8NDwwPDQ8MDw0PDA8NDw0ODQ8MDw0PDA8NDw0ODQ8MDw0PDA8NDw0ODQ8MDw4ODQ4NDwwPDQ8NDg0PDCoNDw0ODQ8MDw0pDigNDwwQDCoMDw0ADQU=
       #Powerful
       - b64:JgB2AGs2DA8NDw0pDQ8NKQ0ODQ8MDw4pDSkNDg0PDA8NKQ4pDQ4MEAwPDQ8NDg0PDQ4NDwwPDQ8MDw0PDQ4NKQ4ODQ4NDwwPDg4NDg4ODCoNDwwPDQ8MKgwPDg4MKg0pDSkODgwPDg4MKg0pDg4NDg4ODCoNKQ4ADQU=
    entity_id: remote.office_remote
  mode: single

- alias: Office Heat Pump Heat
  description: ''
  trigger:
  - platform: time
    at: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: 'sensor.dark_sky_apparent_temperature'
        below: 50
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
  action:
  - service: remote.send_command
    data:
      device: Heat Pump
      command:
       #Power On
       - b64:JgAGAWw1Dg0PDQ4oDg4OKA4NDg4ODQ0pDygODQ4ODg0OKA8nDw0ODg4NDg4ODQ4ODg0ODg4NDg4ODQ4ODg0OKA8NDg0PDQ4NDw0ODQ8NDigODg4NDg4ODQ4oDygOKA4oDigOKA4oDygODQ4ODigODQ8NDg0PDQ4NDw0ODQ8NDigOKA4ODg0OKA8NDg0PDQ4NDw0OKA4ODg0ODg4oDg0PDQ4NDw0ODQ8NDg0PDQ4ODigODQ4ODg0ODg4NDg4ODQ4ODg0PDQ4NDw0ODQ8NDg0ODg4NDw0ODQ8NDg0PDQ4NDw0ODg4NDg4MDw4ODg0ODg4NDigPDQ4NDigPKA4NDigPJw8NDigODg4ADQU=
       #Set Mode Heat
       - b64:JgAGAWo3DQ8MDw0pDQ8MKg0ODQ8MEAwqDSkNDg0PDA8OKQ0pDA8NDwwPDQ8MDw0PDQ4NDwwPDQ8MDw4ODA8NKg0ODQ8MDw0PDA8NDwwPDSkODg0ODQ8MDw0qDSkNKQ0pDSkNKQ4pDSkNDg0PDCoNDg0PDA8NDw0ODQ8NDwwPDCoNKQ4ODA8NDwwPDQ8NDg0qDQ4NKQ4ODQ4ODg0pDBAMDw0PDA8NDwwPDBAMDw0PDSkNDg4ODA8NDwwPDQ8MDw0PDQ4NDwwPDg4MDw4ODBANDgwQDA8MEA0ODBANDg0PDA8NDwwPDQ8MDw0PDA8NDw0ODSkNDw0ODQ8NDg4pDSkNDg0PDCoNDwwADQU=
       #Set Temp 74
       - b64:JgAGAWo2DQ8NDg4oDg4MKg0PDA8NDwwqDSkNDwwPDQ8MKg0pDQ4ODgwPDQ8NDg4ODA8NDw0PDA8MEAwPDBAMKgwPDQ8MDw0PDQ4NDwwPDigNDw0PDQ4NDw0pDSkNKQ0pDSkNKg0pDSkNDg0PDCoNDw0ODQ8NDg0PDQ4NDw0ODSkOKA4ODQ8MDwwQDA8NDwwqDSkMKg0PDA8NDwwPDQ8NDg4ODQ4ODg0ODg4NDg4ODSkNDwwPDBAMDwwQDA8MEA0ODQ8MDw0PDA8NDwwPDQ8MDw0PDQ4NDw0ODQ8NDg4ODA8ODg0ODQ8MDw4ODQ4NDw0ODSoNDg0PDQ4NDwwPDQ8MKg0pDQ8MDw0ADQU=
       #Swing
       - b64:JgAGAWo3DA8NDwwqDQ8NKQwPDQ8MDw0pDSoNDg0PDQ4NKQ4oDg4MEA0ODBAMDwwQDA8NDwwPDQ8NDg0PDA8NKQ4ODA8ODgwPDg4MDw0PDCoNDwwPDQ8MDw0pDSkNKgwqDSkNKQ0pDigNDwwQDCoNDg0PDA8NDwwPDQ8NDg0PDCoNKQ0PDQ4NDwwPDQ8MDw0pDQ8NKQwQDA8MEAwqDA8NDwwPDg4MDw0PDA8NDwwPDSoNDg0PDA8NDwwPDQ8MDw0PDA8NDw0ODQ8MDw0PDA8NDw0ODQ8MDw0PDA8NDw0ODQ8MDw4ODQ4NDwwPDQ8NDg0PDCoNDw0ODQ8MDw0pDigNDwwQDCoMDw0ADQU=
       #Powerful
       - b64:JgB2AGs2DA8NDw0pDQ8NKQ0ODQ8MDw4pDSkNDg0PDA8NKQ4pDQ4MEAwPDQ8NDg0PDQ4NDwwPDQ8MDw0PDQ4NKQ4ODQ4NDwwPDg4NDg4ODCoNDwwPDQ8MKgwPDg4MKg0pDSkODgwPDg4MKg0pDg4NDg4ODCoNKQ4ADQU=
    entity_id: remote.office_remote
  mode: single
  
- alias: Office Heat Pump Off
  description: ''
  trigger:
  - platform: time
    at: '15:45:00'
  condition:
   - condition: state
     entity_id: binary_sensor.workday_sensor
     state: 'on'
  action:
  - service: remote.send_command
    data:
      device: Heat Pump
      command: b64:JgB2AGo3Dg0NDw4oDg0PKAwPDBAMDw0pDSkNDw4NDQ8MKg0pDQ8ODQ0PDA8ODgwPDQ8MDw0PDg0NDwwPDQ8MKg4ODA8NDw4NDQ8ODQ0PDCoODQ0PDg0NDw4oDQ8MDw0PDA8NDwwPDSkODgwqDCoNKQ0qDigOKA4ADQU=
    entity_id: remote.office_remote
  mode: single