script:
  prep_mancave:
    alias: 'Prep the Man Cave'
    sequence:
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
#           device: Heat Pump
           command:
            - b64:JgAGAWo3DQ4ODg0pDQ4OKA4ODQ8NDg0pDigODg0ODg4NKQwqDQ8NDg0PDQ4MEA0ODg4MDw4ODQ4ODg0ODg4MKg0ODg4MDw4ODA8NDwwPDSkODgwPDg4MDw0qDCoNKQ0pDSkOKA0pDikNDg4ODSkNDg4ODA8ODgwPDQ8MDw0PDSkNKQ4ODQ4NKQ4ODA8NDw0pDQ4OKQwPDBAMDwwqDQ8MDw0PDA8NDwwPDQ8MDw0PDA8NDwwPDQ8MDw0PDA8NDwwPDQ8MDw0PDA8NDwwPDQ8MDw0PDA8NDwwPDQ8MDw0PDA8NDwwPDQ8MDw0PDA8NDwwPDSkNDwwQDCoMKgwPDSkNKgwPDSkNDwwADQU=
            - b64:JgAGAWs0Dg0PDQ4oDw0OKA8MDw0ODQ8nDygPDA8NDg0PJw8nEAwODQ8NDg0PDQ4NDw0PDA8NDg0PDQ4NDw0PJw8NDg0PDQ4NDw0ODQ8NDigPDA8NDg0PDQ4oDycPJw8nECcOKA4oDycPDQ4NDycPDQ4NDw0ODRAMDg0PDQ4NECYPKA4NDw0ODQ8NDg0PDQ4oDwwPJw8oDwwPDQ4NDw0ODQ8NDg0PDQ4NDw0ODQ8NDigPDA8NDg0PDQ4ODg0ODQ8NDwwPDQ4NDw0ODQ8NDwwPDQ4NDw0PDA8NDwwPDQ8MDw0PDQ4NDwwPDQ8MEAwPDQ4NDycPDQ4NDw0ODQ8NDg0PJw8NDigPJw8ADQU=
            - b64:JgAGAWo1Dg0PDQ4oDg0PJw8NDg0PDQ4oDycPDQ4NDw0OKA4oDw0ODQ8NDg0PDQ4NDw0ODQ8NDg0PDQ4NDw0OKA4NEAwODQ8NDg0PDQ4NDycPDQ8MDw0PDA8oDigOKA4oDycPJw8oDycODQ8NDikNDQ8NDg0PDQ4NDw0PDA8NDigPJw8NDg0PDQ8MDw0ODQ8nEAwOKA8NDg0PDQ4oDg0PDQ4NDw0ODQ8NDg0PDQ4NDycPDQ4NDw0ODQ8NDg0PDQ8MDw0PDA8NDwwPDQ8MDw0PDA8NDwwPDQ8MDw0PDA8NDwwPDQ8NDg0PDQ4NDw0ODQ8NDigODQ8NDg0PDQ4oDigPDA8NDycPDQ4ADQU=
            - b64:JgAGAWo0Dw0PDA8oDg0PJw8NDg0PDQ4oDigPDQ4NDw0OKA8nDg0PDQ4NDw0ODQ8NDg0PDQ4NDw0PDA8NDwwPKA4NDw0ODQ8NDg0PDQ4NDycQDA4NDw0ODQ8oDigOKA8nDycPJw8nDygODQ8NDigODQ8NDg0PDQ4NDw0ODQ8NDigOKA8NDg0PDQ4NDw0ODQ8nDw0OKA4oDw0ODQ8nDw0ODQ8NDg0PDQ4NDw0ODQ8NDigPDQ4NDw0ODQ8NDg0PDQ4NDw0ODQ8NDg0PDQ4NDw0ODQ8NDg0PDQ4NDw0ODQ8NDg0PDQ4NDw0ODQ8NDg0PDQ4NDygODQ4NDw0ODQ8oDigODQ8NDigOKA8ADQU=
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
#           device: projector
           command: b64:JgBgAAABJpIUERQ2FBEUERQ2FDYUERQRFDYUERQ2FDYUERQRFDYUNhITFDYUERQRFBEUERQRFBESOBQRFDYUNhI4FDYSOBQ2FAAFAwABJUoTAAw9AAEoSBQADDwAAShJEgANBQAAAAAAAA==
         
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
#           device: receiver
           command:
            - b64:JgDKAms4DQ4ODg0qDQ4NKg4ODSoODg0ODikODg0ODSoOKQ4ODQ8NDg0PDQ4ODg0PDA8OKQ4ODSoNDg0PDQ4NKg4ODikODg0ODQ8MDw0PDQ8NDg0PDA8OKQ4ODQ4NDw0qDg4NDg0PDQAJZW03Dg4NDw0qDQ4OKQ4ODSoNDg4ODSoNDg4ODSoOKQ4ODQ4NDw0ODg4NDw0ODQ8NKg0ODikODg0PDQ4NKw0ODCsNDg4ODQ4NDw0PDQ4NDw0ODQ8NKg4ODA8NDw0qDQ4NDw0ODQAJZ2s4Dg4NDg0qDg4MKw0ODSoODg0PDCsNDg0PDCsNKg0ODQ8NDg0PDQ8MDw4ODA8NKg4ODSoNDwwPDQ8NKg0ODSoODg0ODg4NDw0ODQ8MDw0PDQ8MKw0ODQ8MDw0qDg4NDg0PDQAJZms4Dg4MDw0qDg4NKg0PDCsNDg4ODCsNDg4ODSoNKg0ODg4NDwwPDQ8NDg0PDQ8NKg0ODikODgwPDQ8NKg0ODikODg4ODA8NDwwPDQ8NDwwPDQ8MKw0ODg4NDg0qDg4NDwwPDQAJZms4Dg4NDwwqDg4NKg4ODCsNDg0PDSoNDg0PDSoNKg0PDQ4NDwwPDQ8NDg4ODQ8NKg0ODSoODg0ODQ8NKg0ODikODg0PDA8NDwwPDQ8NDwwPDQ8MKw0ODQ8MDw0qDg4NDw0ODQAJZmw3Dg4NDw0qDQ4NKg4ODSoNDg4ODSoNDw0ODSoOKQ4ODA8NDw0ODg4NDwwPDQ8MKw0ODikODg0ODg4NKg4ODCsNDg0PDQ4NDw0PDQ4NDwwPDQ8NKg0ODQ8NDwwrDQ4ODgwPDQAJZmw5DA4PDQ0qDQ8NKg0ODSoODg0ODSoODg0ODykNKQ4ODw0MDw0PDA8PDQ0ODg4NKg0PDikNDg4ODg0NKg4ODSoNDg4ODw0ODQ8NDg0PDQ8MDw0NKg4ODA8PDQ0qDQ4PDQ8MDwANBQAAAAAAAAAAAAAAAA==
            - b64:JgDMAGw2Dw0NDg0qDg4MKw4NDSoPDQ0ODSoODg0PDCsOKQ0ODg4MDw0PDQ4NDw0PDA8OKQ8NDCsODQ0PDQ4NKw4oDw0NDwwrDQ4NKg8oDg4NKg4NDQ8NDg0PDSoOKQ4pDg4NKg0ODQAJZW03Dg4NDwwrDg0NKw0ODCsNDg0PDSoODQ0PDSoNKg0PDg0NDwwPDQ8NDg0PDQ8MKw4NDSoPDQwPDQ8NKg4pDwwNDw0qDw0MKw4pDg0NKg8NDg0NDw0PDikOKQ4pDg0PKA8NDgANBQAAAAAAAAAAAAA=
        
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
#           device: roku
           command: b64:JgBKABEeAAEqlRMTEzgTExM4ExMTOBM4EzgTExIUEjgTExMTExMTOBM4EzgTOBMTExMTExIUExMSExMTExMTOBM4EzgTOBM4EzgTAA0FAAAAAAAAAAAAAAAA
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
#           device: bar tv
           command: b64:JgBsAU0UJxQUEygTFBQoExMUExQoExQUExQUExQAA1FQEygTFBQnFBQTKBMUExQUJxQTFBQTFBMUAANRUBMoFBMUJxQTFCkSFBQTFCcUFBMUExMVEwADUk8UJxQTFCgTFBMoFBMUExQoExQTFBQTFBMAA1JPFCgTFBMoExQUJxQTFBQTKBMUFBMUFBMUAANRUBMoExQUJxQTFCgTFBMUFCcUExQUExQUEwADUk8UJxQTFCgTFBMoExQUExQnFBQTFBQTFBMAA1JPFCgTFBMoExQUJxQTFBQTKBQTFBMUFBMUAANSTxMpEhQUJxQUEygTFRITFScUFBMUExQUEwADUk8UJxQUEygTFBQnFBIVFBMoExQUExQTFBQAA1FPFCgTExUnFBMUKBMUExQUJxQTFBMUFBQTAANSTxQnFBQTKRIUEygUFBMTFCgTFBMUFBMUFAADUVESJxQVEicVExQnFBQTFRMoExIVFRIVEhQADQUAAAAAAAAAAAAA
     
      - service: input_boolean.turn_on
        data: {}
        entity_id: input_boolean.alexa_bar_lights
        
  shut_down_mancave:
    alias: 'Shut Down the Man Cave'
    sequence:
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
#           device: Heat Pump
           command: b64:JgB2AGszEAwPDQ4oDg0PJw8NDg0PDQ4oDycPDQ4NDw0OKA4oDwwPDQ8MDw0PDQ4NDw0ODQ8NDg0PDQ4NDw0OKA4NDw0ODQ8NDg0PDQ4NDycQDA4NEAwPDA8oDg0PDQ4NDw0ODQ8NDigODQ8nDygPJw8nDigPJxAADQU=
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
#           device: projector
           command: 
            - b64:JgBYAAABJJQTEhI4EhMSExM3EjgTEhITEjgSExI4EjgSExMSEjgTNxITEjgTOBE6EBMSOBMSEhMSOBITEhMSExI4EhMSOBI4EgAFAwABJksSAAw9AAEmShIADQUAAAAAAAAAAAAAAAAAAA==
            - b64:JgBYAAABJJQTEhI4EhMSExM3EjgTEhITEjgSExI4EjgSExMSEjgTNxITEjgTOBE6EBMSOBMSEhMSOBITEhMSExI4EhMSOBI4EgAFAwABJksSAAw9AAEmShIADQUAAAAAAAAAAAAAAAAAAA==
         
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
#           device: receiver
           command: b64:JgDKAms4DQ4ODg0qDQ4NKg4ODSoODg0ODikODg0ODSoOKQ4ODQ8NDg0PDQ4ODg0PDA8OKQ4ODSoNDg0PDQ4NKg4ODikODg0ODQ8MDw0PDQ8NDg0PDA8OKQ4ODQ4NDw0qDg4NDg0PDQAJZW03Dg4NDw0qDQ4OKQ4ODSoNDg4ODSoNDg4ODSoOKQ4ODQ4NDw0ODg4NDw0ODQ8NKg0ODikODg0PDQ4NKw0ODCsNDg4ODQ4NDw0PDQ4NDw0ODQ8NKg4ODA8NDw0qDQ4NDw0ODQAJZ2s4Dg4NDg0qDg4MKw0ODSoODg0PDCsNDg0PDCsNKg0ODQ8NDg0PDQ8MDw4ODA8NKg4ODSoNDwwPDQ8NKg0ODSoODg0ODg4NDw0ODQ8MDw0PDQ8MKw0ODQ8MDw0qDg4NDg0PDQAJZms4Dg4MDw0qDg4NKg0PDCsNDg4ODCsNDg4ODSoNKg0ODg4NDwwPDQ8NDg0PDQ8NKg0ODikODgwPDQ8NKg0ODikODg4ODA8NDwwPDQ8NDwwPDQ8MKw0ODg4NDg0qDg4NDwwPDQAJZms4Dg4NDwwqDg4NKg4ODCsNDg0PDSoNDg0PDSoNKg0PDQ4NDwwPDQ8NDg4ODQ8NKg0ODSoODg0ODQ8NKg0ODikODg0PDA8NDwwPDQ8NDwwPDQ8MKw0ODQ8MDw0qDg4NDw0ODQAJZmw3Dg4NDw0qDQ4NKg4ODSoNDg4ODSoNDw0ODSoOKQ4ODA8NDw0ODg4NDwwPDQ8MKw0ODikODg0ODg4NKg4ODCsNDg0PDQ4NDw0PDQ4NDwwPDQ8NKg0ODQ8NDwwrDQ4ODgwPDQAJZmw5DA4PDQ0qDQ8NKg0ODSoODg0ODSoODg0ODykNKQ4ODw0MDw0PDA8PDQ0ODg4NKg0PDikNDg4ODg0NKg4ODSoNDg4ODw0ODQ8NDg0PDQ8MDw0NKg4ODA8PDQ0qDQ4PDQ8MDwANBQAAAAAAAAAAAAAAAA==
        
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
#           device: roku
           command: b64:JgBKABEeAAEqlRMTEzgTExM4ExMTOBM4EzgTExIUEjgTExMTExMTOBM4EzgTOBMTExMTExIUExMSExMTExMTOBM4EzgTOBM4EzgTAA0FAAAAAAAAAAAAAAAA
           
      - service: remote.send_command
        data:
           entity_id: remote.man_cave_remote
           device: bar tv
           command: b64:JgBsAU0UJxQUEygTFBQoExMUExQoExQUExQUExQAA1FQEygTFBQnFBQTKBMUExQUJxQTFBQTFBMUAANRUBMoFBMUJxQTFCkSFBQTFCcUFBMUExMVEwADUk8UJxQTFCgTFBMoFBMUExQoExQTFBQTFBMAA1JPFCgTFBMoExQUJxQTFBQTKBMUFBMUFBMUAANRUBMoExQUJxQTFCgTFBMUFCcUExQUExQUEwADUk8UJxQTFCgTFBMoExQUExQnFBQTFBQTFBMAA1JPFCgTFBMoExQUJxQTFBQTKBQTFBMUFBMUAANSTxMpEhQUJxQUEygTFRITFScUFBMUExQUEwADUk8UJxQUEygTFBQnFBIVFBMoExQUExQTFBQAA1FPFCgTExUnFBMUKBMUExQUJxQTFBMUFBQTAANSTxQnFBQTKRIUEygUFBMTFCgTFBMUFBMUFAADUVESJxQVEicVExQnFBQTFRMoExIVFRIVEhQADQUAAAAAAAAAAAAA
      
      - service: input_boolean.turn_off
        data: {}
        entity_id: input_boolean.alexa_bar_lights
    
input_boolean:
  alexa_bar_lights:
    name: "Bar Lights"
    icon: "mdi:lamp"
    
binary_sensor:
  - platform: template
    sensors:
      alexa_bar_lights:
        friendly_name: "Bar Lights"
        device_class: garage_door
        value_template: "{{ is_state('input_boolean.alexa_bar_lights', 'on')
}}"