sensor:
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
      - alerts
      - feelslike_f
      - elevation
      - location
      - observation_time
      - precip_today_in
      - precip_1d_in
      - precip_2d_in
      - precip_3d_in
      - precip_4d_in
      - station_id
      - temp_f
      - weather
      - wind_mph
      - wind_gust_mph

group:
  daily_forecast:
    name: Wunderground Forecast
    entities:
    - sensor.weather_1d
    - sensor.weather_1n
    - sensor.weather_2d
    - sensor.weather_2n
    - sensor.weather_3d
    - sensor.weather_3n
    - sensor.weather_4d
    - sensor.weather_4n