sensor:
  - platform: darksky
    api_key: !secret darksky_key
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - icon
      - temperature
      - precip_type
      - precip_probability
      - precip_accumulation
      - apparent_temperature
      - wind_speed
      - wind_gust
      - cloud_cover
      - humidity
      - daily_summary
      - temperature_high
      - temperature_low
      - sunrise_time
      - sunset_time
      
